// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAGXw9u5IW7XYRLdAtmAqaKFd81QVMA840',
    appId: '1:673518820823:web:001e332d22215663523f92',
    messagingSenderId: '673518820823',
    projectId: 'flash-chat-6543a',
    authDomain: 'flash-chat-6543a.firebaseapp.com',
    storageBucket: 'flash-chat-6543a.appspot.com',
    measurementId: 'G-JTV2Y1E676',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAxsV8pfAA6404sDKQ9PnlJZ5DYTa1psIs',
    appId: '1:673518820823:android:f835ab64df8a29a6523f92',
    messagingSenderId: '673518820823',
    projectId: 'flash-chat-6543a',
    storageBucket: 'flash-chat-6543a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBIsSWW5wyWqC_yevtHnPxPpvK7QqUW4CA',
    appId: '1:673518820823:ios:e1ada4d0a090dc24523f92',
    messagingSenderId: '673518820823',
    projectId: 'flash-chat-6543a',
    storageBucket: 'flash-chat-6543a.appspot.com',
    iosBundleId: 'com.example.flashchat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBIsSWW5wyWqC_yevtHnPxPpvK7QqUW4CA',
    appId: '1:673518820823:ios:73fb717a772b0277523f92',
    messagingSenderId: '673518820823',
    projectId: 'flash-chat-6543a',
    storageBucket: 'flash-chat-6543a.appspot.com',
    iosBundleId: 'com.example.flashchat.RunnerTests',
  );
}
